### ISSUE TITLE
suggest change project name to servicex

### ISSUE THREAD

**Issue by jiacheo** [servicex-sh/httpx#1]
1. There's already a popular tool named 'httpx' : https://github.com/encode/httpx
2. stackoverflow tagged 'httpx' referrence to the Python one, will confuse some user searching for help.
3. There's no popular project named 'servicex'
4. This tool use for testing several kinds of service, not just for http, so...

**Comment by linux-china** [comment]
Yes, conflict is good choice.  Done.
