### ISSUE TITLE
Please implement urlencode format parsing

### ISSUE THREAD

**Issue by tixsys** [servicex-sh/httpx#6]
Please implement this feature

https://youtrack.jetbrains.com/issue/IDEA-281753/Support-formatting-for-POST-request-body-for-application-x-www-f

Will be much helpful

**Comment by linux-china** [comment]
Released on https://github.com/servicex-sh/httpx/releases/tag/v0.32.0  

This feature is only for CLI, and not available in JetBrains IDE.
